# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse422(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, errors: object=None):  # noqa: E501
        """InlineResponse422 - a model defined in Swagger

        :param errors: The errors of this InlineResponse422.  # noqa: E501
        :type errors: object
        """
        self.swagger_types = {
            'errors': object
        }

        self.attribute_map = {
            'errors': 'errors'
        }
        self._errors = errors

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse422':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_422 of this InlineResponse422.  # noqa: E501
        :rtype: InlineResponse422
        """
        return util.deserialize_model(dikt, cls)

    @property
    def errors(self) -> object:
        """Gets the errors of this InlineResponse422.


        :return: The errors of this InlineResponse422.
        :rtype: object
        """
        return self._errors

    @errors.setter
    def errors(self, errors: object):
        """Sets the errors of this InlineResponse422.


        :param errors: The errors of this InlineResponse422.
        :type errors: object
        """

        self._errors = errors
