# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, student: object=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param student: The student of this InlineResponse200.  # noqa: E501
        :type student: object
        """
        self.swagger_types = {
            'student': object
        }

        self.attribute_map = {
            'student': 'student'
        }
        self._student = student

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def student(self) -> object:
        """Gets the student of this InlineResponse200.


        :return: The student of this InlineResponse200.
        :rtype: object
        """
        return self._student

    @student.setter
    def student(self, student: object):
        """Sets the student of this InlineResponse200.


        :param student: The student of this InlineResponse200.
        :type student: object
        """

        self._student = student
