# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, student_id: int=None, course_id: int=None, status: bool=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param student_id: The student_id of this InlineResponse2001.  # noqa: E501
        :type student_id: int
        :param course_id: The course_id of this InlineResponse2001.  # noqa: E501
        :type course_id: int
        :param status: The status of this InlineResponse2001.  # noqa: E501
        :type status: bool
        """
        self.swagger_types = {
            'student_id': int,
            'course_id': int,
            'status': bool
        }

        self.attribute_map = {
            'student_id': 'student_id',
            'course_id': 'course_id',
            'status': 'status'
        }
        self._student_id = student_id
        self._course_id = course_id
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def student_id(self) -> int:
        """Gets the student_id of this InlineResponse2001.


        :return: The student_id of this InlineResponse2001.
        :rtype: int
        """
        return self._student_id

    @student_id.setter
    def student_id(self, student_id: int):
        """Sets the student_id of this InlineResponse2001.


        :param student_id: The student_id of this InlineResponse2001.
        :type student_id: int
        """

        self._student_id = student_id

    @property
    def course_id(self) -> int:
        """Gets the course_id of this InlineResponse2001.


        :return: The course_id of this InlineResponse2001.
        :rtype: int
        """
        return self._course_id

    @course_id.setter
    def course_id(self, course_id: int):
        """Sets the course_id of this InlineResponse2001.


        :param course_id: The course_id of this InlineResponse2001.
        :type course_id: int
        """

        self._course_id = course_id

    @property
    def status(self) -> bool:
        """Gets the status of this InlineResponse2001.


        :return: The status of this InlineResponse2001.
        :rtype: bool
        """
        return self._status

    @status.setter
    def status(self, status: bool):
        """Sets the status of this InlineResponse2001.


        :param status: The status of this InlineResponse2001.
        :type status: bool
        """

        self._status = status
