# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class StudentAddBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, student_id: int=None, course_id: int=None, phone: int=None):  # noqa: E501
        """StudentAddBody - a model defined in Swagger

        :param student_id: The student_id of this StudentAddBody.  # noqa: E501
        :type student_id: int
        :param course_id: The course_id of this StudentAddBody.  # noqa: E501
        :type course_id: int
        :param phone: The phone of this StudentAddBody.  # noqa: E501
        :type phone: int
        """
        self.swagger_types = {
            'student_id': int,
            'course_id': int,
            'phone': int
        }

        self.attribute_map = {
            'student_id': 'student_id',
            'course_id': 'course_id',
            'phone': 'phone'
        }
        self._student_id = student_id
        self._course_id = course_id
        self._phone = phone

    @classmethod
    def from_dict(cls, dikt) -> 'StudentAddBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The student_add_body of this StudentAddBody.  # noqa: E501
        :rtype: StudentAddBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def student_id(self) -> int:
        """Gets the student_id of this StudentAddBody.


        :return: The student_id of this StudentAddBody.
        :rtype: int
        """
        return self._student_id

    @student_id.setter
    def student_id(self, student_id: int):
        """Sets the student_id of this StudentAddBody.


        :param student_id: The student_id of this StudentAddBody.
        :type student_id: int
        """

        self._student_id = student_id

    @property
    def course_id(self) -> int:
        """Gets the course_id of this StudentAddBody.


        :return: The course_id of this StudentAddBody.
        :rtype: int
        """
        return self._course_id

    @course_id.setter
    def course_id(self, course_id: int):
        """Sets the course_id of this StudentAddBody.


        :param course_id: The course_id of this StudentAddBody.
        :type course_id: int
        """

        self._course_id = course_id

    @property
    def phone(self) -> int:
        """Gets the phone of this StudentAddBody.


        :return: The phone of this StudentAddBody.
        :rtype: int
        """
        return self._phone

    @phone.setter
    def phone(self, phone: int):
        """Sets the phone of this StudentAddBody.


        :param phone: The phone of this StudentAddBody.
        :type phone: int
        """

        self._phone = phone
